### ISSUE TITLE
env.sh does not work on Ubuntu

### ISSUE THREAD

**Issue by KenBarr** [cjwmorgan-sol-sys/solace-samples-qpid-proton-c#1]
the env.sh script starts with:
#!/usr/bin/env sh
Then expects to be in a bash environment, but on ubuntu sh -> dash

Thus produces these errors:
./env.sh make
./env.sh: 1: Bad substitution
./env.sh: 7: source: not found
./env.sh: 10: Bad substitution

ls -l /usr/bin/sh
lrwxrwxrwx 1 root root 4 Nov 18 12:35 /usr/bin/sh -> dash

lsb_release -a | grep Description
No LSB modules are available.
Description:    Ubuntu 19.10

Workaround is to edit first line to read:
#!/usr/bin/env bash

**Comment by cjwmorgan-sol** [comment]
Fixed in #2.
Merged to master closing.
